# ══════════════════════════════════════════════════════════════
#  CONFIGURACIÓN – Identity Service
#  Quarkus 3.9 · Puerto 8083
# ══════════════════════════════════════════════════════════════

quarkus.http.port=8083
quarkus.application.name=identity-service
quarkus.application.version=1.0.0

quarkus.rest-client.crypto-service.url=http://localhost:8081
quarkus.rest-client.crypto-service.connect-timeout=5000
quarkus.rest-client.crypto-service.read-timeout=10000

quarkus.log.level=INFO
quarkus.log.category."com.bcp.dac".level=DEBUG
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) %s%e%n

quarkus.smallrye-openapi.path=/api/v1/openapi
mp.openapi.extensions.smallrye.info.title=Identity Service API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=Gestión de identidad con DNI y Email cifrados
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

quarkus.smallrye-health.root-path=/health
